### ISSUE TITLE
Implement default toJSON

### ISSUE THREAD

**Issue by unlight** [phenomnomnominal/ineeda#4]
If I do `JSON.stringify` on proxy it fails:
```
Uncaught (in promise): Error: 
            "toJSON" is not implemented.
```
Please, add default implementation of toJSON as:
```
toJSON() {
    return ({ prop1, prop2, ... });
}
```

**Comment by phenomnomnominal** [comment]
@unlight I just pushed a version `@0.8.0-beta.0`, let me know if that's what you imagined.
